import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css'

import { Theme } from '@radix-ui/themes'
import { NavigationBar } from '@/components/navigation-bar'
import { Footer } from '@/components/footer'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('h-full scrollbar-hide', inter.className)}>
        <Theme
          accentColor='iris'
          className='h-full'
        >
          <NavigationBar />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  )
}
